In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
a = [[0.6, 0.3, 0.3], 
     [0.3, 0.4, 0.5], 
     [0.1, 0.3, 0.2]]

#This is the Markov TPM.
A = np.array(a)
A

array([[0.6, 0.3, 0.3],
       [0.3, 0.4, 0.5],
       [0.1, 0.3, 0.2]])

In [3]:
eigen_system = la.eig(A)

In [4]:
eigen_values = eigen_system[0]
eigen_vectors = eigen_system[1]

In [5]:
eigen_values

array([ 1. ,  0.3, -0.1])

In [6]:
dom_eigvec = eigen_vectors[:,0]

In [7]:
sum(dom_eigvec)

-1.6586971098088306

In [8]:
#Steady State Prob for the TPM.
q = np.array([each / sum(dom_eigvec) for each in dom_eigvec])
q

array([0.42857143, 0.37662338, 0.19480519])

In [9]:
def entropy(x):
    '''
    Calculate entropy of a system, row-wise.
    '''
    return sum([-1*each*np.log2(each) for each in x])

In [10]:
entropy([0.5, 0.25, 0.25])

1.5

In [11]:
#Transpose matrix so that each row is a valid distribution. 
A.T

array([[0.6, 0.3, 0.1],
       [0.3, 0.4, 0.3],
       [0.3, 0.5, 0.2]])

In [12]:
entropy([0.6, 0.3, 0.1])

1.295461844238322

In [14]:
h = [entropy(e) for e in A.T] #row wise entropy
#Sunny, Cloudy, Rainy
h

[1.295461844238322, 1.5709505944546684, 1.4854752972273344]

In [17]:
#Entropy of the Markov System
print('The Entropy of the System is: {:.3f} bits'.format(np.dot(h, q)))

The Entropy of the System is: 1.436 bits
