In [1]:
import numpy as np

In [2]:
# Transistion States from Problem
#a 000 -> 001

#b 001 -> 010, 011 (f) This is casual linkage, dont have to distingusih between 001 and 101
#f 101 -> 010, 011 (b)

#c 010 -> 100, 101 (g) This is casual linkage, dont have to distingusih between 010 and 110
#g 110 -> 100, 101 (c)

#d 011 -> 110, 111
#e 100 -> 000, 001

#h 111 -> 110
# You can remove the redundant patterns to get 6 unique ones.

In [3]:
#a 000 -> 001
#b *01 -> 010, 011 
#c *10 -> 100, 101  
#d 011 -> 110, 111
#e 100 -> 000, 001
#f 111 -> 110
#Construct a TPM based on these data (Example of Lossy)
# (a, b), (b, c), (b, d), (c, e), (c, b), 
# (d, c), (d, f), (e, a), (e, b), (f, c) 

a = \
[[0, 1, 0, 0, 0, 0],
[0, 0, 1/2, 1/2, 0, 0],
[0, 1/2, 0, 0, 1/2, 0],
[0, 0, 1/2, 0, 0, 1/2],
[1/2, 1/2, 0, 0, 0, 0],
[0, 0, 1, 0, 0 ,0]]
A = np.array(a)
A.T

array([[0. , 0. , 0. , 0. , 0.5, 0. ],
       [1. , 0. , 0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5, 0. , 1. ],
       [0. , 0.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. ]])

In [4]:
eigen_system = np.linalg.eig(A.T)
eigen_system

(array([ 1.        +0.j        , -0.67660498+0.j        ,
         0.08830249+0.60141041j,  0.08830249-0.60141041j,
        -0.25      +0.4330127j , -0.25      -0.4330127j ]),
 array([[ 0.15430335+0.00000000e+00j, -0.28433915+0.00000000e+00j,
         -0.31365673-9.41350667e-02j, -0.31365673+9.41350667e-02j,
         -0.20412415-3.53553391e-01j, -0.20412415+3.53553391e-01j],
        [ 0.6172134 +0.00000000e+00j,  0.52067538+0.00000000e+00j,
         -0.48400201+0.00000000e+00j, -0.48400201-0.00000000e+00j,
         -0.20412415+3.53553391e-01j, -0.20412415-3.53553391e-01j],
        [ 0.6172134 +0.00000000e+00j, -0.52067538+0.00000000e+00j,
          0.48400201+1.70923766e-17j,  0.48400201-1.70923766e-17j,
         -0.20412415+3.53553391e-01j, -0.20412415-3.53553391e-01j],
        [ 0.3086067 +0.00000000e+00j, -0.38477058+0.00000000e+00j,
         -0.05783428+3.93897566e-01j, -0.05783428-3.93897566e-01j,
          0.40824829+0.00000000e+00j,  0.40824829-0.00000000e+00j],
        [ 0.3086

In [5]:
eigen_values = eigen_system[0]
real_evalues = list(np.real(eigen_values))
real_evalues

[1.0,
 -0.6766049820996621,
 0.08830249104983132,
 0.08830249104983132,
 -0.24999999999999992,
 -0.24999999999999992]

In [6]:
eigen_vectors = eigen_system[1]
#np.real(eigen_vectors[:,0]).reshape(len(eigen_vectors[:,0]), 1)
eigen_vec_list = np.real(eigen_vectors[:, np.argmax(real_evalues)])
eigen_vec_list

array([0.15430335, 0.6172134 , 0.6172134 , 0.3086067 , 0.3086067 ,
       0.15430335])

In [7]:
steady_state_tpm = np.array([each/sum(eigen_vec_list) for each in eigen_vec_list])
steady_state_tpm.reshape(len(steady_state_tpm), 1)

array([[0.07142857],
       [0.28571429],
       [0.28571429],
       [0.14285714],
       [0.14285714],
       [0.07142857]])

In [8]:
q = steady_state_tpm
q

array([0.07142857, 0.28571429, 0.28571429, 0.14285714, 0.14285714,
       0.07142857])

In [9]:
def entropy(x):
    return sum([-1*each*np.log2(each) for each in x])

In [10]:
entropy(q)

2.3787834934861753